baseURL = 'https://twuttiwat.github.io/'
title = 'TW Blog'
pagination.pagerSize = 10
theme = 'Terminal'
publishDir = 'docs'
languageCode = 'en-us'

[params]
googleAnalyticsID = 'G-8W769DNB5L'

[params.homeInfoParams]
  Title = 'Hello ðŸ‘‹.'
  Content = 'My name is Teerawat Wuttiwat. I am an [old software engineer](./cv.pdf "Shameless CV link")  who loves to code in F# or any functional programming languages.'

[[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/twuttiwat"

[[params.socialIcons]]
  name = "Twitter"
  url = "https://twitter.com/twuttiwat"  

[[params.socialIcons]]
  name = "CV"
  url = "https://twuttiwat.com/cv.pdf"    

[caches]
  [caches.images]
    dir = ':cacheDir/images'
